### ISSUE TITLE
LP 5.0.0 does not play well with ExtraContexts

### ISSUE THREAD

**Issue by SlimeDog** [LuckPerms/ExtraContexts#12]
Spigot 1.14.4 (Jenkins 2494)
LuckPerms 5.0.0
ExtraContexts 1.0-b11

On server start-up:
```
[12:57:38] [Server thread/ERROR]: Could not load 'plugins/ExtraContexts-1.0-b11.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: me/lucko/luckperms/api/context/ContextCalculator
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:253) [spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:350) [spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: me/lucko/luckperms/api/context/ContextCalculator
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.api.context.ContextCalculator
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.14.4.jar-2019-11-22-1736:git-Spigot-56f8471-ccd47a5]
        ... 6 more
```

**Comment by Tobi406** [comment]
See the wiki: https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5#api-compatibility

**Comment by SlimeDog** [comment]
```
You have two options for fixing this:

Ask the author of the plugin to update to support the new API version. (preferred)
```
since the author is Luck, I assume that the preferred option will result in the desired outcome.

**Comment by Andre601** [comment]
> ```
> You have two options for fixing this:
> 
> Ask the author of the plugin to update to support the new API version. (preferred)
> ```
> 
> since the author is Luck, I assume that the preferred option will result in the desired outcome.

You completely forgot the second option which is to download and use the legacy-api jar to have a temporary fix for this issue.
I'm sure Luck will update this when many people use it, but in the meantime, should you just use the legacy jar as a workaround.

**Comment by SlimeDog** [comment]
I didn't forget. It doesn't work for ExtraContexts. (I does work for PlaceholderAPI).

**Comment by mibby** [comment]
I'm also hopeful for a quick fix from @lucko. Unfortunately the legacy extensions jar does not work for me either with ExtraContexts.

```
[02:26:41] [Server thread/ERROR]: Could not load 'plugins/ExtraContexts.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: me/lucko/luckperms/api/context/ContextCalculator
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) ~[paperclip.jar:git-Purpur-322]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:235) ~[paperclip.jar:git-Purpur-322]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:878) ~[paperclip.jar:git-Purpur-322]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NoClassDefFoundError: me/lucko/luckperms/api/context/ContextCalculator
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_232]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[paperclip.jar:git-Purpur-322]
	... 6 more
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.api.context.ContextCalculator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[paperclip.jar:git-Purpur-322]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_232]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[paperclip.jar:git-Purpur-322]
	... 6 more
```

**Comment by lucko** [comment]
Hmm that is odd, the legacy extension should be working for this.

**Comment by lucko** [comment]
Ok I see the issue, not super easy to fix for now.

Anyway, I've updated ExtraContexts, should work now.

**Comment by SlimeDog** [comment]
I don't find the update in the usual place: [https://ci.lucko.me/job/ExtraContexts/](https://ci.lucko.me/job/ExtraContexts/).

Link please.

**Comment by lucko** [comment]
Just triggered a build :)

**Comment by SlimeDog** [comment]
I misunderstood. Thanks. Confirmed issue resolved in b12.
