### ISSUE TITLE
ExtraContexts placed in 'plugins' doesn't load, generates error

### ISSUE THREAD

**Issue by gmalone** [LuckPerms/ExtraContexts#16]
I'm running Paper 1.14.4 v.231, and placing ExtraContexts into 'plugins' results in the following error, and thus doesn't load:

`[09:36:56 ERROR]: Could not load 'plugins\ExtraContexts.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/luckperms/api/context/ContextCalculator
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138) ~[patched_1.14.4.jar:git-Paper-231]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337) ~[patched_1.14.4.jar:git-Paper-231]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257) ~[patched_1.14.4.jar:git-Paper-231]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) ~[patched_1.14.4.jar:git-Paper-231]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-231]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-231]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.NoClassDefFoundError: net/luckperms/api/context/ContextCalculator
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_221]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63) ~[patched_1.14.4.jar:git-Paper-231]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.14.4.jar:git-Paper-231]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: net.luckperms.api.context.ContextCalculator
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.4.jar:git-Paper-231]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-231]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_221]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_221]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63) ~[patched_1.14.4.jar:git-Paper-231]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.14.4.jar:git-Paper-231]
        ... 6 more`

**Comment by Andre601** [comment]
[default-assignment]: https://github.com/lucko/LuckPerms/wiki/Extensions#extension-default-assignments
[legacy-extension]: https://github.com/lucko/LuckPerms/wiki/Extensions#extension-legacy-api
[update]: https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5
[default-groups]: https://github.com/lucko/LuckPerms/wiki/Default-Groups

# Common v5 issues

## Plugin x spams errors about LuckPerms
If the error contains `Caused by: java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms` then the plugin uses the old v4 API of LuckPerms, while you're using LuckPerms v5.
A solution to this problem is to [download and install the legacy-API extension][legacy-extension] into the `extension` folder located inside the `LuckPerms` folder. If no such folder exist, create it.
Also, please contact the developer of the plugin and ask them to update to the latest release of the LuckPerms API.

If the error however contains `Caused by: java.lang.ClassNotFoundException: net.luckperms.api.LuckPerms` then it is the exact opposite and you're using LuckPerms v4 while the plugin is using LuckPerms v5.
In that case, do you need to update LuckPerms to v5. A page explaining how to migrate from v4 to v5 can be found [here][update].

## The expansion for PlaceholderAPI/MVdWPlaceholderAPI doesn't work
Please refer to the above section for how to solve this.
Just note that the latest version of the expansion is only compatible with LuckPerms v5.

## Default assignments don't work
The default assignments got removed in LuckPerms v5.
A temporary solution is to [download and install the default-assignment exptension][default-assignment] into the `extension` folder located inside the `LuckPerms` folder. If this folder doesn't exist, create it.

This, however, should be treated as a temporary solution and you should switch to an [alternative method][default-groups] instead.

**Comment by lucko** [comment]
Funnily enough none of those "common issues" are the problem here.

You've got a newer version of ExtraContexts and an older version of the plugin. Probably easiest to update the plugin.

You can get the newest version here. https://luckperms.net/

**Comment by Andre601** [comment]
I mean I do mention, that an issue could be new plugin, old api

**Comment by gmalone** [comment]
Thanks.  I’ve updated the plugin.  I appreciate your time. Greg Malonehttps://gregmalone.meSanta Fe, New Mexico From: Andre_601Sent: Saturday, December 14, 2019 11:07To: LuckPerms/ExtraContextsCc: Greg Malone; AuthorSubject: Re: [LuckPerms/ExtraContexts] ExtraContexts placed in 'plugins' doesn't load, generates error (#16) I mean I do mention, that an issue could be new plugin, old api—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
