### ISSUE TITLE
ExtraContexts doesn't work after config

### ISSUE THREAD

**Issue by CyberFlameGO** [LuckPerms/ExtraContexts#17]
I recently changed the config of ExtraContexts from:
```java
# ExtraContexts
# made with <3 by Luck


# Set a provider to true to enable it.
# Contexts are explained in more detail here:
# https://github.com/lucko/LuckPerms/wiki/Context


# Provides the 'wg-region' context.
# Returns the name of each WorldGuard region the player is currently in.
#
# e.g. wg-region=spawn
worldguard: false

# Provides the 'gamemode' context.
# Returns the players current gamemode.
#
# e.g. gamemode=creative
gamemode: false

# Provides the 'dimension' context.
# Returns the type of the players current world.
#
# e.g. dimension=nether
dimension: false

placeholderapi: false
placeholderapi-placeholders:
  allowflight: "%player_allow_flight%"
```
To this:
```java
# ExtraContexts
# made with <3 by Luck


# Set a provider to true to enable it.
# Contexts are explained in more detail here:
# https://github.com/lucko/LuckPerms/wiki/Context


# Provides the 'wg-region' context.
# Returns the name of each WorldGuard region the player is currently in.
#
# e.g. wg-region=spawn
worldguard: true

# Provides the 'gamemode' context.
# Returns the players current gamemode.
#
# e.g. gamemode=creative
gamemode: true

# Provides the 'dimension' context.
# Returns the type of the players current world.
#
# e.g. dimension=nether
dimension: true

placeholderapi: true
placeholderapi-placeholders:
  allowflight: "%player_allow_flight%"
```
and added ChatControl Pro. I'm not sure what's wrong.

**Comment by CyberFlameGO** [comment]
I forgot \# had a Markdown value so I edited everything into codeblocks

**Comment by Andre601** [comment]
Are there any errors in the console?
Also, what version of LuckPerms, ExtraContexts and server (including server type) are you using?

**Comment by CyberFlameGO** [comment]
I use PaperSpigot (443) 1.8.8 with LuckPerms 5.0.39 and ExtraContexts (2.0-SNAPSHOT) Build #12. I just restarted my server and when loading ExtraContexts I get this error output:
```java
[22:04:19] [Server thread/INFO]: [ExtraContexts] Enabling ExtraContexts v2.0-SNAPSHOT
[22:04:19] [Server thread/INFO]: [ExtraContexts] Registering 'worldguard' calculator.
[22:04:19] [Server thread/ERROR]: Error occurred while enabling ExtraContexts v2.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/registry/FlagConflictException
	at me.lucko.extracontexts.libs.worldguardwrapper.WorldGuardWrapper.<init>(WorldGuardWrapper.java:38) ~[?:?]
	at me.lucko.extracontexts.libs.worldguardwrapper.WorldGuardWrapper.getInstance(WorldGuardWrapper.java:20) ~[?:?]
	at me.lucko.extracontexts.calculators.WorldGuardCalculator.<init>(WorldGuardCalculator.java:18) ~[?:?]
	at me.lucko.extracontexts.ExtraContextsPlugin.register(ExtraContextsPlugin.java:38) ~[?:?]
	at me.lucko.extracontexts.ExtraContextsPlugin.onEnable(ExtraContextsPlugin.java:26) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-443]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-443]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-443]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-443]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-443]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-443]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-443]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-443]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-443]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-443]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.flags.registry.FlagConflictException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched.jar:git-PaperSpigot-443]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-443]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
	... 16 more
[22:04:19] [Server thread/INFO]: [ExtraContexts] Disabling ExtraContexts v2.0-SNAPSHOT
```
I also use WorldGuard 6.1 and PlaceholderAPI 2.10.4

**Comment by Andre601** [comment]
Try using WorldGuard 7 as it can't find a class from WorldGuard, meaning it does use a different API.
And v7 of WorldGuard had their API path changed a bit.

**Comment by CyberFlameGO** [comment]
I thought WorldGuard 7 wasn't available for 1.8.8

**Comment by Andre601** [comment]
I don't know. I don't use 1.8.8 and from what I know do the devs of WorldGuard suggest to always update your server, which I support.

**Comment by CyberFlameGO** [comment]
I use 1.8.8 because I hate anything upwards of it. Is there any other solution?

**Comment by CyberFlameGO** [comment]
I guess it's time to move on from 1.8.8, so I'm closing this issue
