### ISSUE TITLE
Warning in console

### ISSUE THREAD

**Issue by beamer91** [LuckPerms/ExtraContexts#25]
Am running paper build #350, luckperms bukkit 5.1.32, and at the time of writing the latest extracontext available. when ever a player joins the console gets spammed with:
[19:20:23] [Server thread/WARN]: [LuckPerms] An exception was thrown by me.lucko.extracontexts.calculators.PlaceholderApiCalculator whilst calculating the context of subject CraftPlayer{name=thebeamer91}
[19:20:23] [Server thread/WARN]: java.lang.NullPointerException
[19:20:23] [Server thread/WARN]: 	at com.plotsquared.bukkit.placeholder.Placeholders.onPlaceholderRequest(Placeholders.java:65)
[19:20:23] [Server thread/WARN]: 	at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:41)
[19:20:23] [Server thread/WARN]: 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:326)
[19:20:23] [Server thread/WARN]: 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:525)
[19:20:23] [Server thread/WARN]: 	at me.lucko.extracontexts.calculators.PlaceholderApiCalculator.calculate(PlaceholderApiCalculator.java:27)
[19:20:23] [Server thread/WARN]: 	at me.lucko.extracontexts.calculators.PlaceholderApiCalculator.calculate(PlaceholderApiCalculator.java:12)
[19:20:23] [Server thread/WARN]: 	at me.lucko.luckperms.common.context.ContextManager.calculate(ContextManager.java:138)
[19:20:23] [Server thread/WARN]: 	at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:54)
[19:20:23] [Server thread/WARN]: 	at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:42)
[19:20:23] [Server thread/WARN]: 	at me.lucko.luckperms.common.cache.ExpiringCache.get(ExpiringCache.java:64)
[19:20:23] [Server thread/WARN]: 	at me.lucko.luckperms.common.context.QueryOptionsCache.getQueryOptions(QueryOptionsCache.java:59)
[19:20:23] [Server thread/WARN]: 	at me.lucko.luckperms.bukkit.inject.permissible.LuckPermsPermissible.hasPermission(LuckPermsPermissible.java:175)
[19:20:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:232)
[19:20:23] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Permissions.PermissionsManager$CMIPerm.hasPermission(PermissionsManager.java:439)
[19:20:23] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Permissions.PermissionsManager$CMIPerm.hasPermission(PermissionsManager.java:415)
[19:20:23] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Permissions.PermissionsManager$CMIPerm.hasPermission(PermissionsManager.java:411)
[19:20:23] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Permissions.PermissionsManager$CMIPerm.hasPermission(PermissionsManager.java:391)
[19:20:23] [Server thread/WARN]: 	at com.Zrips.CMI.AllListeners.WorldLimits.processGameMode(WorldLimits.java:49)
[19:20:23] [Server thread/WARN]: 	at com.Zrips.CMI.AllListeners.WorldLimits.onLoginGameMode(WorldLimits.java:35)
[19:20:23] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor580.execute(Unknown Source)
[19:20:23] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[19:20:23] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[19:20:23] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:20:23] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[19:20:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerList.attemptLogin(PlayerList.java:622)
[19:20:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:154)
[19:20:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:65)
[19:20:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:339)
[19:20:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:140)
[19:20:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1353)
[19:20:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[19:20:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181)
[19:20:23] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
[19:20:23] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by lucko** [comment]
Seems to be a PlotSquared issue - their placeholder expansion is throwing a NPE here:

`com.plotsquared.bukkit.placeholder.Placeholders.onPlaceholderRequest(Placeholders.java:65)`
