### ISSUE TITLE
Spam in console

### ISSUE THREAD

**Issue by WolverStones** [LuckPerms/ExtraContexts#32]
[LuckPerms] An exception was thrown by me.lucko.extracontexts.calculators.WorldGuardFlagCalculator whilst calculating the context of subject CraftPlayer{name=Mastereve}

Worldguard 7.0.5 (https://builds.enginehub.org/job/worldguard/16384)

WorldguardExtraFlags 4.1.4

Server Paper 1.16.3
Build 251

Worldedit FastAsyncWorldEdit-1.16-362

**Comment by emilyy-dev** [comment]
Does the issue still ocurr if you use WorldEdit instead of FAWE?

**Comment by WolverStones** [comment]
> Does the issue still ocurr if you use WorldEdit instead of FAWE?

I'll try and let you know.

**Comment by WolverStones** [comment]
I tried to use Worldedit no Fawe and the problem is still the same (spam)

**Comment by emilyy-dev** [comment]
Mind pasting the entire server latest log in http://gist.github.com/ or https://bytebin.lucko.me/ (or any paste site for that matter)? You can find the entire log in `logs/latest.log`

**Comment by WolverStones** [comment]
This is a new error

`[LuckPerms] An exception was thrown by me.lucko.extracontexts.calculators.WorldGuardFlagCalculator whilst calculating the context of subject CraftPlayer{name=WolverStone}
[23:34:30] [pool-62-thread-2/WARN]: java.lang.NullPointerException
[23:34:30] [pool-62-thread-2/WARN]: 	at me.lucko.extracontexts.calculators.WorldGuardFlagCalculator.calculate(WorldGuardFlagCalculator.java:29)
[23:34:30] [pool-62-thread-2/WARN]: 	at me.lucko.extracontexts.calculators.WorldGuardFlagCalculator.calculate(WorldGuardFlagCalculator.java:21)
[23:34:30] [pool-62-thread-2/WARN]: 	at me.lucko.luckperms.common.context.ContextManager.calculate(ContextManager.java:138)
[23:34:30] [pool-62-thread-2/WARN]: 	at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:54)
[23:34:30] [pool-62-thread-2/WARN]: 	at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:42)
[23:34:30] [pool-62-thread-2/WARN]: 	at me.lucko.luckperms.common.cache.ExpiringCache.get(ExpiringCache.java:64)
[23:34:30] [pool-62-thread-2/WARN]: 	at me.lucko.luckperms.common.context.QueryOptionsCache.getQueryOptions(QueryOptionsCache.java:59)
[23:34:30] [pool-62-thread-2/WARN]: 	at me.lucko.luckperms.common.context.ContextManager.getQueryOptions(ContextManager.java:82)
[23:34:30] [pool-62-thread-2/WARN]: 	at me.lucko.luckperms.common.api.implementation.ApiContextManager.getQueryOptions(ApiContextManager.java:87)
[23:34:30] [pool-62-thread-2/WARN]: 	at me.lucko.luckperms.placeholders.LPPlaceholderProvider.onPlaceholderRequest(LPPlaceholderProvider.java:283)
[23:34:30] [pool-62-thread-2/WARN]: 	at me.lucko.luckperms.placeholders.LuckPermsExpansion.onPlaceholderRequest(LuckPermsExpansion.java:68)
[23:34:30] [pool-62-thread-2/WARN]: 	at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:31)
[23:34:30] [pool-62-thread-2/WARN]: 	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156)
[23:34:30] [pool-62-thread-2/WARN]: 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69)
[23:34:30] [pool-62-thread-2/WARN]: 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:97)
[23:34:30] [pool-62-thread-2/WARN]: 	at me.neznamy.tab.platforms.bukkit.PluginHooks.setPlaceholders(PluginHooks.java:30)
[23:34:30] [pool-62-thread-2/WARN]: 	at me.neznamy.tab.platforms.bukkit.BukkitMethods$6.get(BukkitMethods.java:212)
[23:34:30] [pool-62-thread-2/WARN]: 	at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.update(PlayerPlaceholder.java:23)
[23:34:30] [pool-62-thread-2/WARN]: 	at me.neznamy.tab.shared.features.PlaceholderManager$1.run(PlaceholderManager.java:83)
[23:34:30] [pool-62-thread-2/WARN]: 	at me.neznamy.tab.shared.cpu.CPUManager$4.run(CPUManager.java:119)
[23:34:30] [pool-62-thread-2/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:34:30] [pool-62-thread-2/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:34:30] [pool-62-thread-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[23:34:30] [pool-62-thread-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[23:34:30] [pool-62-thread-2/WARN]: 	at java.lang.Thread.run(Thread.java:748`


Full file: (lates.log)

https://gist.github.com/WolverStones/1e6b6137aa9360931c14081bd5a34583

**Comment by emilyy-dev** [comment]
Try using a version of WorldEdit that supports your server version. 7.1.0 doesn't support 1.16.3, try with 7.2.0-rc-2.

**Comment by WolverStones** [comment]
I tried it but it still writes the same thing anyway last log > https://gist.github.com/WolverStones/70434def3c293704560da7276c9c63a3

**Comment by emilyy-dev** [comment]
I can't seem to replicate the issue, mind testing with [this build of ExtraContexts](https://cdn.discordapp.com/attachments/710101199642165249/772642728571306014/ExtraContexts.jar)?

**Comment by WolverStones** [comment]
Can't it have something to do with, for example, the region's priority?
 
Tonight i will testing if it has nothing to do with any plugin or region settings, and I'll get back to you.

I use this build https://ci.lucko.me/job/ExtraContexts/14/

**Comment by WolverStones** [comment]
`[LuckPerms] An exception was thrown by me.lucko.extracontexts.calculators.WorldGuardFlagCalculator whilst calculating the context of subject CraftPlayer{name=digglet_}
[23:34:35 WARN]: java.lang.NullPointerException
[23:34:35 WARN]: at me.lucko.extracontexts.calculators.WorldGuardFlagCalculator.calculate(WorldGuardFlagCalculator.java:29)
[23:34:35 WARN]: at me.lucko.extracontexts.calculators.WorldGuardFlagCalculator.calculate(WorldGuardFlagCalculator.java:21)
[23:34:35 WARN]: at me.lucko.luckperms.common.context.ContextManager.calculate(ContextManager.java:138)
[23:34:35 WARN]: at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:54)
[23:34:35 WARN]: at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:42)
[23:34:35 WARN]: at me.lucko.luckperms.common.cache.ExpiringCache.get(ExpiringCache.java:64)
[23:34:35 WARN]: at me.lucko.luckperms.common.context.QueryOptionsCache.getQueryOptions(QueryOptionsCache.java:59)
[23:34:35 WARN]: at me.lucko.luckperms.bukkit.inject.permissible.LuckPermsPermissible.hasPermission(LuckPermsPermissible.java:175)
[23:34:35 WARN]: at org.bukkit.craftbukkit.v1_16_R2.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:206)
[23:34:35 WARN]: at com.Zrips.CMI.Modules.Permissions.PermissionsManager$CMIPerm.hasPermission(PermissionsManager.java:451)
[23:34:35 WARN]: at com.Zrips.CMI.Modules.Permissions.PermissionsManager$CMIPerm.hasPermission(PermissionsManager.java:427)
[23:34:35 WARN]: at com.Zrips.CMI.Modules.Permissions.PermissionsManager$CMIPerm.hasPermission(PermissionsManager.java:423)
[23:34:35 WARN]: at com.Zrips.CMI.Modules.Permissions.PermissionsManager$CMIPerm.hasPermission(PermissionsManager.java:403)
[23:34:35 WARN]: at com.Zrips.CMI.AllListeners.PlayerListeners.onChatIgnore(PlayerListeners.java:1269)
[23:34:35 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor840.execute(Unknown Source)
[23:34:35 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[23:34:35 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[23:34:35 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[23:34:35 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[23:34:35 WARN]: at net.minecraft.server.v1_16_R2.PlayerConnection.chat(PlayerConnection.java:1831)
[23:34:35 WARN]: at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1746)
[23:34:35 WARN]: at net.minecraft.server.v1_16_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:41)
[23:34:35 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:34:35 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:34:35 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[23:34:35 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[23:34:35 WARN]: at java.lang.Thread.run(Thread.java:748)`

Ok if I enable 'worldguard-flag: true' in the config, this error will start spamming in the console. it doesn't limit me somehow because I just need worldguard-region: true

Preview flags in regions: https://prnt.sc/vc6ewk (spawn) https://prnt.sc/vc6fl2 (boss_noflyzone) https://prnt.sc/vc6fwh (boss_arena)
I also use worldguardextraflags and flags like glide and fly are used from that plugin 
As for worldedit, it works for me even with fast async worldedit when I turn off worldguard-flag

**Comment by srnyx** [comment]
Is there any fix for this?
