### ISSUE TITLE
NPE on player connect

### ISSUE THREAD

**Issue by SlimeDog** [LuckPerms/ExtraContexts#34]
Spigot 1.16.4 (Jenkins 2960)
Spartan 376.1
WorldGuard 7.0.5-SNAPSHOT+2082-d313f2c
LuckPerms 5.2.41
ExtraContexts 2.0-b15; also 2.0-b16

Twice on player connect, and hundreds of times thereafter, moving between worlds:
```
[21:36:14] [Server thread/WARN]: [LuckPerms] An exception was thrown by me.lucko.extracontexts.calculators.WorldGuardFlagCalculator whilst calculating the context of subject CraftPlayer{name=SlimeDog}
java.lang.NullPointerException: null
        at me.lucko.extracontexts.calculators.WorldGuardFlagCalculator.calculate(WorldGuardFlagCalculator.java:29) ~[?:?]
        at me.lucko.extracontexts.calculators.WorldGuardFlagCalculator.calculate(WorldGuardFlagCalculator.java:21) ~[?:?]
        at me.lucko.luckperms.common.context.ContextManager.calculate(ContextManager.java:138) ~[?:?]
        at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:54) ~[?:?]
        at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:42) ~[?:?]
        at me.lucko.luckperms.common.cache.ExpiringCache.get(ExpiringCache.java:64) ~[?:?]
        at me.lucko.luckperms.common.context.QueryOptionsCache.getQueryOptions(QueryOptionsCache.java:59) ~[?:?]
        at me.lucko.luckperms.bukkit.inject.permissible.LuckPermsPermissible.hasPermission(LuckPermsPermissible.java:175) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:190) ~[spigot-1.16.4.jar-2020-11-20-2045:git-Spigot-a19903d-167ff59]
        at me.vagdedes.spartan.features.c.c.a(Permissions.java:54) ~[?:?]
        at me.vagdedes.spartan.features.g.e.a(ReconnectCooldown.java:29) ~[?:?]
        at me.vagdedes.spartan.f.c.a(EventsHandler3.java:151) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.4.jar-2020-11-20-2045:git-Spigot-a19903d-167ff59]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.4.jar-2020-11-20-2045:git-Spigot-a19903d-167ff59]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.4.jar-2020-11-20-2045:git-Spigot-a19903d-167ff59]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.4.jar-2020-11-20-2045:git-Spigot-a19903d-167ff59]
        at net.minecraft.server.v1_16_R3.PlayerList.attemptLogin(PlayerList.java:547) ~[spigot-1.16.4.jar-2020-11-20-2045:git-Spigot-a19903d-167ff59]
        at net.minecraft.server.v1_16_R3.LoginListener.c(LoginListener.java:134) ~[spigot-1.16.4.jar-2020-11-20-2045:git-Spigot-a19903d-167ff59]
        at net.minecraft.server.v1_16_R3.LoginListener.tick(LoginListener.java:53) ~[spigot-1.16.4.jar-2020-11-20-2045:git-Spigot-a19903d-167ff59]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:219) ~[spigot-1.16.4.jar-2020-11-20-2045:git-Spigot-a19903d-167ff59]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:130) ~[spigot-1.16.4.jar-2020-11-20-2045:git-Spigot-a19903d-167ff59]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1127) ~[spigot-1.16.4.jar-2020-11-20-2045:git-Spigot-a19903d-167ff59]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[spigot-1.16.4.jar-2020-11-20-2045:git-Spigot-a19903d-167ff59]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[spigot-1.16.4.jar-2020-11-20-2045:git-Spigot-a19903d-167ff59]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[spigot-1.16.4.jar-2020-11-20-2045:git-Spigot-a19903d-167ff59]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar-2020-11-20-2045:git-Spigot-a19903d-167ff59]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
ExtraContexts/config.yml
```
# ExtraContexts
# made with <3 by Luck


# Set a provider to true to enable it.
# Contexts are explained in more detail here:
# https://github.com/lucko/LuckPerms/wiki/Context


# Provides the 'worldguard:region' and 'worldguard:in-region' contexts.
# Returns the name of each WorldGuard region the player is currently in.
#
# e.g. worldguard:in-region=true and worldguard:region=spawn
worldguard-region: false

# Provides the 'worldguard:flag-xxx' contexts.
# Returns the value of each flag set by WorldGuard in the region the player is currently in.
#
# e.g. worldguard:flag-build=allow
worldguard-flag: false

# Provides the 'gamemode' context.
# Returns the players current gamemode.
#
# e.g. gamemode=creative
gamemode: false

# Provides the 'whitelisted' context.
# Returns if the player is whitelisted on the server or not.
#
# e.g. whitelisted=true
whitelisted: false

# Provides the 'dimension' context.
# Returns the type of the players current world.
#
# e.g. dimension=nether
dimension: false

# Provides the 'team' context.
# Returns the name of the team the players is in.
#
# e.g. team=pvp-blue
team: false

# Provides the 'has-played-before' context.
# Returns if the player has connected to the server before, or if this is their first time.
#
# e.g. has-played-before=false
has-played-before: false

placeholderapi: false
placeholderapi-placeholders:
  allowflight: "%player_allow_flight%"
```
This did not occur with ExtraContexts b14.

**Comment by SlimeDog** [comment]
NPE issue remains in ExtraContexts b16.

**Comment by Laarryy** [comment]
Does this still happen on 1.17 with the latest versions of WG and Paper/Spigot?

**Comment by SlimeDog** [comment]
I do not see this issue with
```
Spigot 1.17.1-3262 or Paper 1.17.1-338
WorldGuard 7.0.7-SNAPSHOT+2156-9b66513
LuckPerms 5.3.71
ExtraContexts 2.0-b16
```
I have no idea if it still occurs on the reported platform (the report was 11 months ago).

**Comment by Laarryy** [comment]
Thanks SlimeDog, appreciate the confirmation!
