### ISSUE TITLE
Had these WARNS appear

### ISSUE THREAD

**Issue by axemwa** [LuckPerms/ExtraContexts#8]
Had these WARNS appear and spam console only thing I can think of that I did with EC was add exactly this "wg-region=spawn" context for a permission

[14:16:50 WARN]: [LuckPerms] An exception was thrown by me.lucko.extracontexts.calculators.PlaceholderApiCalculator whilst calculating the context of subject CraftPlayer{name=1machinemaker1}
[14:16:50 WARN]: java.lang.IllegalArgumentException: value is (effectively) empty
[14:16:50 WARN]:        at me.lucko.luckperms.api.context.AbstractContextSet.sanitizeValue(AbstractContextSet.java:85)
[14:16:50 WARN]:        at me.lucko.luckperms.api.context.MutableContextSet.add(MutableContextSet.java:255)
[14:16:50 WARN]:        at me.lucko.extracontexts.calculators.PlaceholderApiCalculator.giveApplicableContext(PlaceholderApiCalculator.java:30)
[14:16:50 WARN]:        at me.lucko.extracontexts.calculators.PlaceholderApiCalculator.giveApplicableContext(PlaceholderApiCalculator.java:14)
[14:16:50 WARN]:        at me.lucko.luckperms.common.context.ContextManager.calculate(ContextManager.java:198)
[14:16:50 WARN]:        at me.lucko.luckperms.common.context.ContextsCache.supply(ContextsCache.java:53)
[14:16:50 WARN]:        at me.lucko.luckperms.common.context.ContextsCache.supply(ContextsCache.java:41)
[14:16:50 WARN]:        at me.lucko.luckperms.common.buffer.ExpiringCache.get(ExpiringCache.java:64)
[14:16:50 WARN]:        at me.lucko.luckperms.common.context.ContextsCache.getContexts(ContextsCache.java:58)
[14:16:50 WARN]:        at me.lucko.luckperms.bukkit.inject.permissible.LPPermissible.hasPermission(LPPermissible.java:167)
[14:16:50 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:118)
[14:16:50 WARN]:        at eu.kennytv.maintenance.spigot.listener.PlayerLoginListener.postLogin(PlayerLoginListener.java:47)
[14:16:50 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor765.execute(Unknown Source)
[14:16:50 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[14:16:50 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[14:16:50 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[14:16:50 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[14:16:50 WARN]:        at net.minecraft.server.v1_13_R2.PlayerList.attemptLogin(PlayerList.java:567)
[14:16:50 WARN]:        at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:150)
[14:16:50 WARN]:        at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:66)
[14:16:50 WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:263)
[14:16:50 WARN]:        at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:130)
[14:16:50 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1129)
[14:16:50 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[14:16:50 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[14:16:50 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)

**Comment by lucko** [comment]
Should be fixed in the latest build
